#spring.application.name=discodeit

discodeit:
  repository:
    type: file
    file-directory: .discodeit

  storage:
    type: local
    local:
      root-path: ./attachments/download

spring:
  profiles:
    active: dev

  # To Debug
  jpa:
    open-in-view: false