server {
  listen 80;

  # ^~ : "/"보다 우선적용 /api/로 시작하는 요청은~
  location ^~ /api/ {
    # 요청을 Spring Boot(app의 80번 포트)로 전달
    proxy_pass http://app:80;

    # 요청의 Host 정보를 app:80에 전달(localhost:3000이면 localhost가 나옴)
    proxy_set_header Host $host;

    # 실제 클라이언트 IP를 app:80에 전달
    proxy_set_header X-Real-IP $remote_addr;

    # 클라이언트가 거쳐온 프록시 IP들(0개 이상)과 클라이언트 IP(1개)를 app:80에 전달
    # $proxy_add_x_forwarded_for : X-Forwarded-For(거쳐온 프록시 IP 주소) + $remote_addr(클라이언트 IP)
    # 여기서는 nginx -> app:80 전달이지만 client -> nginx에서 X-Forwarded-For 보내지 않았기 때문에 클라이언트 IP만 존재함
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ^~ /ws/ {
    proxy_pass http://app:80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # WebSocket 업그레이드
    # $http_upgrade는 브라우저가 핸드셰이크를 통해 websocket 값이 됨
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # 명시적으로 버전 표기(WebSocket은 1.1 버전이 필요함)
    proxy_http_version 1.1;
  }

  location / {
    root /usr/share/nginx/html;

    # SPA Fallback
    # $uri $uri/ /index.html 순서대로 확인
    # $uri : 현재 요청 URI 경로가 존재하는지 확인
    # $uri/ : 현재 요청 URI 경로가 디렉토리인지 확인
    # 둘 다 존재하지 않으면 /index.html을 호출
    try_files $uri $uri/ /index.html;
  }
}